### ISSUE TITLE
mysql报错

### ISSUE THREAD

**Issue by 1336461612** [fujie-xiyou/chat_room#1]
当我在Service目录用make编译时，报错了，错误compile Persistence/Account_Persist.c ...
gcc -DDEBUG -c -Wall -Wextra -ggdb3 -I. Persistence/Account_Persist.c -o Persistence/Account_Persist.o 
In file included from Persistence/Account_Persist.c:12:0:
Persistence/MySQL.h:12:24: fatal error: mysql/mysql.h: No such file or directory
 #include<mysql/mysql.h>
                        ^
compilation terminated.
make: *** [Persistence/Account_Persist.o] Error 1

想请教一下你 怎么解决，希望你给点建议！！！

**Comment by tylercross** [comment]
加一

**Comment by fujie-xiyou** [comment]
没安装mysql库  你安装一下libmysql这个库
Ubuntu上：
```sudo apt install libmysql++-dev```
Centos上：
```sudo yum install mysql-devel```
